### ISSUE TITLE
The deers in the Module behave abnormally

### ISSUE THREAD

**Issue by aneeshsharma** [Terasology/WildAnimals#5] opened 2016-12-12 13:41 UTC
The deers when spawned in the world work fine for sometime. They behave very normally and walk fine. But after sometime, they just start flipping rapidly to and fro (at one moment, they head on side and at the other moment, they just flip back - this happens quite rapidly). According to my observations, they start doing this many times when they are on an edge or a wall but sometimes they start this at any place.

Please look into the issue and try to resolve it.

Thank you

**Comment by nihal111** [comment] 2017-03-22 21:13
I can confirm this behavior. @flo @Cervator @skaldarnar do you have any leads for why this happens?

**Comment by flo** [comment] 2017-03-28 22:47
Possibly lack of input events. For the skeleton in gooey's quest I implemented an alternative appraoch but I haven't backported it to the Pathfinding module and thus the Deers yet.

**Comment by flo** [comment] 2017-05-07 12:07
I assume the issue is fixed now since we switched to the behavior system of gooeys quests.

**Closed by flo** 2017-05-07 12:07 UTC
Labels: bug
